version: '3'
services:
  nginx:
    ports:
      - "4000:80"
  node-app:
    environment:
      - PORT=4000
      - MONGO_USERNAME=sanjeev
      - MONGO_PASSWORD=mypassword
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=mysecret
    command: node index.js