version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - MONGO_USERNAME=sanjeev
      - MONGO_PASSWORD=mypassword
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=mysecret
    command: npm run dev